### Get all categories
GET http://localhost:8080/api/categories?page=0&size=10&nameCategory=Alexander%20The%20Great

###

### Get category by ID
GET http://localhost:8080/api/categories/1

###

### Create new category
POST http://localhost:8080/api/categories
Content-Type: application/json

{
  "categoryId": 1,
  "categoryName": "Books of Harry Potter"
}

###

### Update category
PUT http://localhost:8080/api/categories/1
Content-Type: application/json

{
  "categoryName": "Book Of Harry Potter"
}

###

### Delete category
DELETE http://localhost:8080/api/categories/1
